### PR TITLE
Requirement to move upload folder for temporary image

### PR DESCRIPTION
**Pull request by BirenRathod**
The code will help to create folder into sites/sitename/files or sites/default/files for Drupal base websites. as stated in here, -> https://github.com/Indicia-Team/drupal-7-module-iform/issues/8. This development is require to use Drupal base cloud service like Pantheon.

### CODE REVIEW

**Comment by JimBacon** [comment]
I've added a comment to the issue. I wasn't clear which commit in the above list helps to resolve it.

**Comment by BirenRathod** [comment]
@JimBacon 
Thanks for your comment.
I have done the code last week and tested on my machine, I haven't commited here yet, which I'm going to any minute now.

**Comment by johnvanbreda** [comment]
This doesn't look right - why does the pull request have a load of unrelated commits? Please do not merge until sorted.

**Comment by BirenRathod** [comment]
You are right, one possibility could be,  previous commits haven't been merged into develop branch or base branch.

**Comment by BirenRathod** [comment]
I'm not committing until you resolved that. Yes, I'm aware of cache folder bit,so no implementation for that.

**Comment by JimBacon** [comment]
The above is a pull request to merge develop in to master. I.e all commits to develop since the last release. I think it more likely that you want a pull request from your feature branch in to develop which will only contain the commits you have made. When John makes the next release, that is when everything in develop is moved to master.

**Comment by BirenRathod** [comment]
Yes, that's right, I need to create another branch of it. I'm closing this pull request now, if that is OK.

**Pull request closed without merging**
