### PR TITLE
Iss 800 6

### PR DESCRIPTION
**Pull request by burkmarr**
Filter summary control (previously discussed in draft pull request https://github.com/Indicia-Team/client_helpers/pull/102)

### CODE REVIEW

**Comment by johnvanbreda** [comment]
@burkmarr are you OK to resolve the conflicts here before I merge?

**Comment by burkmarr** [comment]
@johnvanbreda - sorry John yes I will take a look at the conflicts - I didn't notice them. I thought I had merged develop into my branch before I pushed.

**Comment by burkmarr** [comment]
I get it - it was because of the other pull request I had which you have merged.

**Comment by burkmarr** [comment]
@johnvanbreda - done.

**Pull request merged**
