### PR TITLE
Requirement to move temporary image folder into files directory.

### PR DESCRIPTION
**Pull request by BirenRathod**
Upload.php file has now got provision to support CORS. This help to use upload feature on Pantheon cloud service.

The path of temporary image has been moved into sites/sitename/files/indicia or sites/default/files/indicia. This features will only useful for Drupal base site.

### CODE REVIEW

**Comment by johnvanbreda** [comment]
Sorry, I don't really agree with this implementation. It doesn't work for Drupal 8. Also, rather than putting code which hacks around to work out a file upload path in various places throughout client helpers, a better way would be to edit function iform_load_helpers for both Drupal 8 and Drupal 7 to set helper_base::$interim_image_folder so that it is available throughout the client helper code. Then you don't need the changes to data_entry_helper.php or helper_base.php. This is then consistent with the way other folder paths are set, e.g. the cache folder. Also, you can use the function hostsite_get_public_file_path() to provide a Drupal version tolerant way of finding where the public file folder is.

On a side note, it would be nice if all code adhered to Drupal coding standards - quite a lot of the indentation for example is random in these changes.

**Comment by BirenRathod** [comment]
Obviously, the function I used is not for Drupal 8. I could write it for that in seperate branch.  One of the problem not to implement code in iform_load_helper is that upload.php dosen't have access of all variables from iForm module. due to that, I chose this way. Bare  in mind that I implemented this code, so it will be useful to use with Drupal & non-drupal site.

**Comment by johnvanbreda** [comment]
It's not the code in upload.php I was looking at - I appreciate the code in upload.php needs to be "clever" to know where it is running (Drupal 7/8 or not in Drupal). But, the code in the data_entry_helper.php and helper_base.php files is not necessary if you just make a simple change to the iform module for both Drupal 7 and 8.

**Comment by BirenRathod** [comment]
I know, I haven't particularly paid attention to for coding standard as less priority to set up in visual studio code.

**Comment by BirenRathod** [comment]
I will change that in iForm module.

**Comment by johnvanbreda** [comment]
In VSCode I have used the phpcs module and it works very well.

**Comment by BirenRathod** [comment]
Thanks and making some necessary changes suggested in https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code.

**Comment by BirenRathod** [comment]
@johnvanbreda 

I have implemented interim_image_folder path in helper_base & data_entry_helper & added the settings for interim image folder in iform.module file.

**Pull request merged**
