### PR TITLE
Add all outstanding ABLE changes to client_helpers

### PR DESCRIPTION
**Pull request by Gary-van-Breda**
(None outstanding for iform or media)

### CODE REVIEW

**Comment by Gary-van-Breda** [comment]
Should this have been against the develop branch?

**Comment by johnvanbreda** [comment]
Master is fine, if the changes have already been applied to develop?

**Comment by Gary-van-Breda** [comment]
See pull request #125 for develop branch version: this branch can probably be ditched, and the dev one used instead.

**Comment by johnvanbreda** [comment]
Closing as will merge to develop then to master from there.

**Pull request closed without merging**
