### PR TITLE
Add all outstanding ABLE changes to client_helpers (dev branch)

### PR DESCRIPTION
**Pull request by Gary-van-Breda**
Add all outstanding ABLE changes to client_helpers

Should replace pull request #124

### CODE REVIEW

**Comment by BirenRathod** [comment]
@johnvanbreda Are you planning to update this on current butterfly-monitoring site?

**Comment by johnvanbreda** [comment]
Yes, soon @BirenRathod

**Comment by BirenRathod** [comment]
@johnvanbreda if it is possible please use Drupal 9 branch. I have already added you on it. I have already setup Drupal 9 and migrated all stuff on it. I'm waiting @DavidRoy to decide stop using Drupal 8 site and start using Drupal 9 one.

**Comment by BirenRathod** [comment]
@johnvanbreda Here are the URLs of the Drupal 9 one.
http://dev-brc-ebms.pantheonsite.io/
http://test-brc-ebms.pantheonsite.io/
http://live-brc-ebms.pantheonsite.io/

**Pull request merged**
